
services:
    neo4j:
      image: neo4j:community-bullseye
      environment:
        - NEO4J_AUTH=neo4j/rootroot
        - NEO4J_dbms_allow__upgrade=true
        - NEO4J_apoc_export_file_enabled=true
        - NEO4J_apoc_import_file_enabled=true
        - NEO4J_apoc_import_file_use__neo4j__config=true
        - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"]
        - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      ports:
        - 7687:7687
        - 7474:7474
        - 7473:7473