networks:
  cassandra:

services:
  cassandra-1:
    image: cassandra:latest
    container_name: cassandra1
    ports:
      - "9042:9042"  # Cassandra client port
      - "7004:7000"  # Cassandra SSL inter-node communication
      - "7005:7001"  # Cassandra JMX monitoring port
      - "7199:7199"  # Cassandra JMX monitoring port
      - "9160:9160"  # Cassandra Thrift client API
    environment: &environment
      CASSANDRA_SEEDS: "cassandra1,cassandra2"
      CASSANDRA_CLUSTER_NAME: ESGICluster
      CASSANDRA_DC: DC1
      CASSANDRA_RACK: RACK1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_NUM_TOKENS: 128
    volumes:
      - cassandra-1_data:/var/lib/cassandra:rw
      - ./scripts:/script
    networks:
      - cassandra
    hostname: cassandra1
    healthcheck:
      test: [ "CMD-SHELL", "nodetool status" ]
      interval: 2m
      start_period: 2m
      timeout: 10s
      retries: 3

  cassandra-2:
    image: cassandra:latest
    container_name: cassandra2
    ports:
      - "9043:9042"  # Cassandra client port
      - "7006:7000"  # Cassandra inter-node communication
      - "7007:7001"  # Cassandra SSL inter-node communication
      - "7198:7199"  # Cassandra JMX monitoring port
      - "9161:9160"  # Cassandra Thrift client API
    volumes:
      - cassandra-2_data:/var/lib/cassandra:rw
    networks:
      - cassandra
    hostname: cassandra2
    environment: *environment
    depends_on:
      cassandra-1:
        condition: service_started
    healthcheck:
      test: [ "CMD-SHELL", "nodetool status" ]
      interval: 2m
      start_period: 2m
      timeout: 10s
      retries: 3

volumes:
  cassandra-1_data:
  cassandra-2_data:
